package fr.imacaron.flashplayerrevival.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFD0253C)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_secondary = Color(0xFFD9687B)
val md_theme_dark_onSecondary = Color(0xFF680014)
val md_theme_dark_secondaryContainer = Color(0xFF920020)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_tertiary = Color(0xFFFFB3B2)
val md_theme_dark_onTertiary = Color(0xFF680014)
val md_theme_dark_tertiaryContainer = Color(0xFF920020)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFFD0253C)
val md_theme_dark_onBackground = Color(0xFFFFDADB)
val md_theme_dark_surface = Color(0xFFFFFFFF)
val md_theme_dark_onSurface = Color(0xFFD0253C)
val md_theme_dark_surfaceVariant = Color(0xFF524343)
val md_theme_dark_onSurfaceVariant = Color(0xFF666666)
val md_theme_dark_outline = Color(0xFFA08C8C)
val md_theme_dark_inverseOnSurface = Color(0xFF40000E)
val md_theme_dark_inverseSurface = Color(0xFFFFDADB)
val md_theme_dark_inversePrimary = Color(0xFFBC1130)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B2)
val md_theme_dark_outlineVariant = Color(0xFF524343)
val md_theme_dark_scrim = Color(0xFF000000)
